

name: Java CI with Maven and deploy to EC2

on:
  push:
    branches: [ "deploy-to-EC2" ]
  pull_request:
    branches: [ "deploy-to-EC2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build Docker image
      run: docker build -t bikashshah15/testspringbootapp1 .

    - name: Publish image to Docker Hub
      run: docker push bikashshah15/testspringbootapp1:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Check Docker Permissions
        run: sudo usermod -aG docker $(whoami)

      - name: Pull Image from Docker Hub
        run: docker pull bikashshah15/testspringbootapp1:latest

      - name: Delete old container
        run: docker rm -f testspringbootapp1 || true

      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name testspringbootapp1 bikashshah15/testspringbootapp1:latest